package nl

const (
	LWTUNNEL_IP6_UNSPEC = iota
	LWTUNNEL_IP6_ID
	LWTUNNEL_IP6_DST
	LWTUNNEL_IP6_SRC
	LWTUNNEL_IP6_HOPLIMIT
	LWTUNNEL_IP6_TC
	LWTUNNEL_IP6_FLAGS
	LWTUNNEL_IP6_PAD
	LWTUNNEL_IP6_OPTS
)
