#!/bin/bash

if test -f "/etc/iproute2/rt_protos"; then
if ! grep -q 254 "/etc/iproute2/rt_protos"; then
    echo -e "254\tmetalbond" >> "/etc/iproute2/rt_protos"
fi
fi

chown -R metalbond:metalbond /usr/share/metalbond